---
- name: Crete New User
  hosts: nodeAppServer
  tasks:
  - name: Create linux User
    user:
      name: awaden
      comment: this is my personal user
      group: admin

- name: Test awaden User
  hosts: nodeAppServer
  become: True
  become_user: awaden
  tasks:
  - name: Create mohamed Folder
    command:
      cmd: mkdir mohamed